// generated by deja install — safe to delete; regenerate with: deja install deepseek-auto
import { execFileSync } from "node:child_process";

const DEJA = "C:\\Users\\27063\\.dsh\\profiles\\web\\node_modules\\@vshulcz\\deja-vu-windows-amd64\\bin\\deja.exe";

// Memory is optional: a plugin that throws in an assembly ends the turn, so
// every call deja makes is swallowed to "".
function ask(args, payload) {
  try {
    return execFileSync(DEJA, args, {
      input: JSON.stringify(payload),
      encoding: "utf8",
      timeout: 10000,
      maxBuffer: 4 * 1024 * 1024,
      stdio: ["pipe", "pipe", "ignore"],
    }).trim();
  } catch {
    return "";
  }
}

function recall(prompt, cwd) {
  return ask(["hook-prompt", "--plain"], { prompt, cwd });
}

function sessionId(agent) {
  return (agent && (agent.sessionId || (agent.session && agent.session.id))) || "";
}

// The workspace a session belongs to. One web or tui process serves sessions
// from every workspace and never changes directory, so process.cwd() is only
// where dsh was launched; the session header carries the directory the session
// was opened in.
function sessionCwd(agent) {
  const header = agent && agent.session && agent.session.header;
  return (header && header.cwd) || process.cwd();
}

// The project digest, once at the start of the session. deja_once keys the
// one-shot on the session id in deja's ledger, which survives a resume in a new
// process; the Set is the in-process guard that keeps the long-lived web and
// tui profiles from spawning deja on every assembly of a session already shown.
function projectDigest(agent, seen) {
  const sid = sessionId(agent);
  if (sid && seen.has(sid)) return "";
  if (sid) seen.add(sid);
  return ask(["hook-context", "--plain"], {
    session_id: sid,
    cwd: sessionCwd(agent),
    source: "startup",
    deja_once: true,
  });
}

function userText(message) {
  const content = message && message.content;
  if (!Array.isArray(content)) return typeof content === "string" ? content.trim() : "";
  return content
    .filter((part) => part && part.type === "text" && typeof part.text === "string")
    .map((part) => part.text)
    .join("\n")
    .trim();
}

function isHuman(message) {
  return Boolean(message) && (!message.source || message.source.kind === "user");
}

function lastHumanText(agent) {
  const events = agent && agent.session && agent.session.events;
  if (!Array.isArray(events)) return "";
  for (let i = events.length - 1; i >= 0; i--) {
    const event = events[i];
    if (!event) continue;
    if (event.type === "user/message" && isHuman(event.data)) return userText(event.data);
    if (event.type === "agent/inbox/spliced") {
      const inserted = event.data && event.data.inserted;
      if (!Array.isArray(inserted)) continue;
      for (let j = inserted.length - 1; j >= 0; j--) {
        if (isHuman(inserted[j])) return userText(inserted[j]);
      }
    }
  }
  return "";
}

function apply(ctx) {
  let asked = "";
  let askedIn = "";
  let recalled = "";
  const digestSeen = new Set();

  // A second copy of this file in the same profile — the npm package next to
  // the installer's, a --patch overlay naming it again — makes the host throw
  // "prompt context deja:recall is already registered", and that takes the
  // whole profile down: no agent at all, over an optional memory plugin.
  // One registration is all recall needs, so the loser stands down quietly.
  //
  // Two contexts are registered. deja:project is what this project settled,
  // once at the start of the session, ordered ahead of the per-prompt recall so
  // it reads as background rather than an answer to the question.
  // agent/session-start is emit-only — its return reaches nothing — so the
  // digest rides the same assembly seam the recall does, gated to one turn per
  // session.
  try {
    ctx.systemPrompt.context({
      name: "deja:project",
      order: 110,
      text: (assembly) => {
        const agent = assembly && assembly.agent;
        if (!agent) return "";
        return projectDigest(agent, digestSeen);
      },
    });
    ctx.systemPrompt.context({
      name: "deja:recall",
      order: 120,
      text: (assembly) => {
        const agent = assembly && assembly.agent;
        if (!agent) return "";
        const prompt = lastHumanText(agent);
        if (!prompt) return "";
        const cwd = sessionCwd(agent);
        // The same question asked in another workspace is a different question.
        if (prompt !== asked || cwd !== askedIn) {
          asked = prompt;
          askedIn = cwd;
          recalled = recall(prompt, cwd);
        }
        // Silence is the common case: this speaks only when the history answers.
        return recalled;
      },
    });
  } catch {}
}

apply.inject = ["systemPrompt"];

export default apply;
