// generated by deja install — safe to delete; regenerate with: deja install deepseek
import { execFileSync } from "node:child_process";

const DEJA = "C:\\Users\\27063\\.dsh\\profiles\\web\\node_modules\\@vshulcz\\deja-vu-windows-amd64\\bin\\deja.exe";

function apply(ctx) {
  // Loaded twice in one profile the host throws "command deja is already
  // registered" and the whole profile fails to load, which costs the user
  // their agent over a duplicate search command. One /deja is enough.
  try {
  ctx.commands.register({
    name: "deja",
    description: "Search this machine's past AI coding sessions",
    input: { hint: "what to look for" },
    async handler(invocation) {
      const query = String((invocation && invocation.rawInput) || "").trim();
      if (!query) {
        return { kind: "error", text: "Say what to look for: /deja <error, file, or decision>" };
      }
      // "search" is named rather than handed over as deja's first word: the
      // bare-query path dispatches a word that happens to be a command, so
      // /deja version printed a version number and /deja index rebuilt the
      // index. "--" then keeps a query that starts with a dash from being read
      // as a flag, which came back as an error the caller cannot tell from an
      // empty history.
      const args = query.startsWith("-") ? ["search", "--", query] : ["search", query];
      try {
        const out = execFileSync(DEJA, args, {
          encoding: "utf8",
          timeout: 20000,
          maxBuffer: 4 * 1024 * 1024,
          stdio: ["ignore", "pipe", "ignore"],
        }).trim();
        return { kind: "success", text: out || "Nothing in this machine's history matches that." };
      } catch (err) {
        return { kind: "error", text: "deja: " + String((err && err.message) || err) };
      }
    },
  });
  } catch {}
}

apply.inject = ["commands"];

export default apply;
